---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - williamyeh.prometheus
    - Stouts.grafana
    - Guidewire.blackbox-exporter
    - stuff
  vars:
    prometheus_components:
      - "node_exporter"
      - "prometheus"
      - "alertmanager"

    prometheus_node_exporter_version: 0.13.0
    prometheus_version: 1.5.2
    prometheus_alertmanager_version:  0.5.1
    grafana_version:  4.1.2-1486989747
    blackbox_version: 0.4.0

    prometheus_use_systemd: true
    prometheus_node_exporter_opts: "-collectors.enabled diskstats,entropy,loadavg,meminfo,time,stat,conntrack,uname,filesystem,netdev,netstat,sockstat"
    prometheus_conf_main: "roles/stuff/files/prometheus.yml"
    prometheus_alertmanager_url: "http://{{ansible_default_ipv4.address}}:9093"
    prometheus_rule_files:
      InstanceDown:
        src:  roles/williamyeh.prometheus/files/basic.rules
        dest: basic.rules

    grafana_domain: localhost
    grafana_reporting_enabled: false
    grafana_external_enabled: false
    grafana_dashboard_json_enabled: true

    blackbox_install_dir: '/opt/prometheus/blackbox_exporter'
    blackbox_config_file: '/etc/prometheus/blackbox.yml'
    blackbox_pid_file: /var/run/prometheus/blackbox.pid
    blackbox_log_file: /var/log/prometheus/blackbox.log

    test_backends:
    - 'meetup.com'
